spring:
  redis:
    host: redis
    port: 6379
  rabbitmq: # RabbitMQ 관련 설정
    host: 3.38.31.74
    port: 5672
    username: bts
    password: "{cipher}e23db7ec02ab706c93bee68f4f2637c81fc7681d55d6481d128e9cb3535409d2"
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: "{cipher}66ee26adde6a9b4bc2ced5eaf0e4ea9d5a1c75b90129ada380c9171105320439469f4dac8d857dce40cd759c6a4daa2a318e07fa73df2df6bcac0156fb6a5d68"
            client-secret: "{cipher}2523cff77e81b4be9e0a3b01c81efb95d8f58c638491a8f82decdda979d43abb989698b49052d553976a3a95aa204358b8b558233d16a99d37242aa49176d534"
            redirect-uri: "http://bithumb-bts.com/login/oauth2/code/kakao"
            client-authentication-method: POST
            authorization-grant-type: "authorization_code"
            scope: profile_nickname, profile_image, account_email
            client-name: Kakao
          naver:
            client-id: "{cipher}e3e27d90b588e56530685c279f6b1135d7c29d63348bb641cf74c6c6ed04a37987c736de8a064ae64b77c13e527b0d19"
            client-secret: "{cipher}e8a7be79ea491e42464906e54a0f5f525c3de85ffe966465476eb884e4c3e1c5"
            redirect-uri: "http://bithumb-bts.com/login/oauth2/code/naver"
            uthorization-grant-type: authorization_code
            scope: name, email, profile_image
            client-name: Naver
        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response
          kakao:
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
    jwt:
      token:
        security-key: "{cipher}e28fb01d77f05afb7981fff27f7eff676a19c80ee896eb0c7ba0cda46d1e0512"

  application:
    name: auth-service
  sleuth:
    enabled: true
    sampler:
      probability: 0.5
  zipkin:
    base-url: http://3.38.28.154:9411/

server:
  port: 8081

eureka:
  instance:
    instance-id: auth-ms-instance
    hostname: 3.35.78.48
    
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://3.38.31.74:8761//eureka

