spring:
  application:
    name: board-server
  data:
    mongodb:
      uri: mongodb://mongo:27017/bts-board-db
server:
  port: 8080

eureka:
  instance:
    instance-id: board-ms-instance
    hostname: localhost

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://3.38.31.74:8761/eureka
