spring:
  application:
    name: auction-consumer
  rabbitmq: # RabbitMQ 관련 설정
    host: 3.38.31.74
    port: 5672
    username: bts
    password: "{cipher}e23db7ec02ab706c93bee68f4f2637c81fc7681d55d6481d128e9cb3535409d2"
  data:
    mongodb:
      uri: mongodb://mongo:27017/bts-auction-db
  kafka:
    consumer:
      bootstrap-servers: 172.17.0.1:9092
      group-id: auction-group_id
eureka:
  instance:
    instance-id: consumer-ms-instance
    hostname: 3.34.239.132
    
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://3.38.31.74:8761/eureka
server:
  port: 9090
