server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://bts-db.crtppt0lvgk7.ap-northeast-2.rds.amazonaws.com:3306/BTS
    username: bts
    password: "{cipher}7efe023e74d6b9e49820e41b868943ed4b66bd77e5632f8c0d9cd50b769ba070"

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

  application:
    name: db-service

eureka:
  instance:
    instance-id: db-ms-instance
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://3.38.31.74:8761/eureka
