server:
  port: 8081
  test: test

spring:
  rabbitmq: # RabbitMQ 관련 설정
    host: localhost
    port: 5672
    username: bts
    password: btsbts12

management:
  endpoints:
    web:
      exposure:
        include: refresh
