server:
  port: 8000

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka:8761/eureka

spring:
  security:
    jwt:
      token:
        security-key: secret-key
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allow-credentials: true
            allowedHeaders:
              - x-requested-with
              - authorization
              - content-type
              - credential
              - token
              - refresh
            allowedMethods:
              - POST
              - GET
              - PUT
              - OPTIONS
              - DELETE
      routes:
        - id: order-ms-instance
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order/**
          filters:
            - GlobalAuthFilter
            - RewritePath=/order/?(?<segment>.*), /$\{segment}

        - id: auth-ms-instance
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/test
          filters:
            - RewritePath=/auth/?(?<segment>.*), /$\{segment}
        - id: auth-ms-instance
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/refresh
          filters:
            - GlobalRefreshFilter
            - RewritePath=/auth/?(?<segment>.*), /$\{segment}