server:
  port: 8000

eureka:
  instance:
    instance-id: gateway-ms-instance


  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka:8761/eureka

spring:
  security:
    jwt:
      token:
        security-key: "{cipher}e28fb01d77f05afb7981fff27f7eff676a19c80ee896eb0c7ba0cda46d1e0512"
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allow-credentials: true
            add-to-simple-url-handler-mapping: true
            allowedHeaders:
              - x-requested-with
              - authorization
              - content-type
              - credential
              - token
              - refresh
            allowedMethods:
              - POST
              - GET
              - PUT
              - OPTIONS
              - DELETE
      routes:
        - id: order-ms-instance
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order/**
          filters:
            - GlobalAuthFilter
            - RewritePath=/order/?(?<segment>.*), /$\{segment}

        - id: auth-ms-instance
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/test
          filters:
            - RewritePath=/auth/?(?<segment>.*), /$\{segment}
        - id: auth-ms-instance
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/refresh
          filters:
            - GlobalRefreshFilter
            - RewritePath=/auth/?(?<segment>.*), /$\{segment}