server:
  port: 9999
spring:
  application:
    name: order-service

eureka:
  instance:
    instance-id: "{cipher}6baaa7bb534782e885b70cfda8b6dd0fbc99e84cb87cb574c4bfa88fa4d259b5bb4deed9a30dbefc9106585819ec1d7784bafc607f9e74fa34cd4cec4a1f64a2"

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

default:
  message: user-service 에서 global profiles 에서 사용할 설정 정보들
