server:
  port: 8888
spring:
  application:
    name: order-service

eureka:
  instance:
    instance-id: order-ms-instance

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
