server:
  port: 8888
spring:
  application:
    name: order-service

eureka:
  instance:
    instance-id: order-ms-instanceteteteterefresg

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

default:
  message: user-service 에서 global profiles 에서 사용할 설정 정보들
