spring:
  application:
    name: auction-producer
  sleuth:
    enabled: true
    sampler:
      probability: 0.5
  zipkin:
    base-url: http://3.38.28.154:9411/
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://bts-database.crtppt0lvgk7.ap-northeast-2.rds.amazonaws.com:3306/auction
    username: bts
    password: btsbts12
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        
  rabbitmq: # RabbitMQ 관련 설정
    host: 3.38.31.74
    port: 5672
    username: bts
    password: "{cipher}e23db7ec02ab706c93bee68f4f2637c81fc7681d55d6481d128e9cb3535409d2"
  kafka:
    producer:
      bootstrap-servers: 172.17.0.1:9092
server:
  port: 8083

eureka:
  instance:
    instance-id: producer-ms-instance
    hostname: 3.36.66.33

  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://3.38.31.74:8761/eureka
